### ISSUE TITLE
Token is null

### ISSUE THREAD

**Issue by apozgaj** [AzureADQuickStarts/AppModelv2-NativeClient-DotNet#1]
Hello,

I've been using AppV2 Model for quite some time but after recent breaking changes regarding the openId scope, my native client stopped working. The problem is that every property including "Token" is null once ADAL is done with issuing a token, therefore the request against my API fails.

I've changed the scope to be "openid profile" etc, I've re-created the app in https://apps.dev.microsoft.com but I still get the same result.

Thanks,
Andrija

**Comment by jmprieur** [comment]
This sample uses MSAL.NET, not ADAL.NET. I'm confused by this issue. Did you add the right platforms? 
The sample works for me with all accounts.
