### ISSUE TITLE
OAuthBearerAuthenticationOptions in .NET 4.6 with Azure AD v2

### ISSUE THREAD

**Issue by jrmcdona** [AzureADQuickStarts/AppModelv2-NativeClient-DotNet#11]
Do you guys have a sample in .NET 4.6 or can give a pointer?

IIssuerSecurityTokenProvider is not longer available in Microsoft.Owin.Security.Jwt.   There is now IIssuerSecurityKeyProvider and OpenIdConnectCachingSecurityTokenProvider is no longer compiling.

Therefore I cannot get OAuthBearerAuthenticationOptions working with an Azure AD v2 endpoint on my Web API.

**Comment by jmprieur** [comment]
@jrmcdona : 
I'll have a look at it
Meanwhile, would you want to look at the following sample? 
https://github.com/azure-samples/active-directory-dotnet-native-aspnetcore-v2
(it's now even a tutorial)

**Comment by jmprieur** [comment]
@jrmcdona 
I just tried the sample (and even with a target framework of .NET 4.6) and I did not get any build error.
Can you please provide repro steps?

**Comment by jrmcdona** [comment]
I am sorry, I didn't give enough info.  The issue isn't just .NET it is with upgraded packages. The issue is when you use upgraded Mi

@jmprieur 
You need to updgrade Microsoft.Owin.Security.Jwt and the related packages and you will start having these problem.

I can look at your other sample although we are not using Core.    

Chris Ross told me this.  See the email thread here:

From: Chris Ross
You need to update OpenIdConnectCachingSecurityTokenProvider and model it after WsFedCachingSecurityKeyProvider.


From: jrmdcona
Thanks, so is that now built in or do I need to essentially take WsFedCachingSecurityKeyProvider and use it like OpenIdConnectCachingSecurityTokenProvider which gets manually added as a class to the project?

From: Chris Ross
Subject: RE: OAuthBearerAuthenticationOptions in .NET 4.6

That’s outdated, it should look something like this now:
https://github.com/aspnet/AspNetKatana/blob/e2b18ec84ceab7ffa29d80d89429c9988ab40144/src/Microsoft.Owin.Security.ActiveDirectory/WsFedCachingSecurityKeyProvider.cs#L18

**Comment by jmprieur** [comment]
Rephrasing what I understand, @jrmcdona 
you are looking for an **ASP.NET 4.x sample** (this one is an ASP.NET 3.x and therefore you should not upgrade System.IdentityModel.Tokens.Jwt, which is already at the latest compatible version)

Is it an option for you to use ASP.NET Core 2.2 . There is a good sample for it: https://github.com/azure-samples/active-directory-dotnet-native-aspnetcore-v2 .
Otherwise I need to produce a new sample ...

**Comment by jmprieur** [comment]
closed by error

**Comment by jrmcdona** [comment]
@jmprieur 
You rephrased correctly.

Core isn't an option right now since we already have a solution built.  I am just adding to it.

The work Chris Ross from ASP.NET teams refered to seems too complicated to me and I have to manually add in classes.

Last night I created Azure AD v1 endpoints and I am going to use ADAL instead of MSAL.
I was hoping to try out the Azure v2 endpoints but I think ADAL will work for now.

Then I will stick with UseWindowsAzureActiveDirectoryBearerAuthentication instead of OAuthBearerAuthenticationOptions.

**Comment by jmprieur** [comment]
But I'm confused, @jrmcdona : you have a Web API? you should use JwtBearerAuthentication? not OAuthBearerAuthentication?

**Comment by jrmcdona** [comment]
@jmprieur  Oh really?  How come I missed that.  I must have assumed it would be the same as what I saw in this sample OAuthBearerAuthenticationOptions.

Yes I have an Angular 6 Front end.   Then we have a .NET backend API.   The two are separated and live on different servers.    We pass over the Bearer token in the header on the requests.  

I can look up JwtBearerAuthentication.      Thanks for mentioning that.

**Comment by jrmcdona** [comment]
@jmprieur That being said do you think I should go with ADAL or MSAL on the microsoft.com tenant?
This will be for internal app.

**Comment by jmprieur** [comment]
For Web APIs accepting tokens for one organization, both would work today, and the changes from ADAL to MSAL would be minimal 
(v2.0 authority essentially)
