### ISSUE TITLE
JwtFormat is missing in Microsoft.Owin.Security.Jwt 4.1

### ISSUE THREAD

**Issue by jrmcdona** [AzureADQuickStarts/AppModelv2-NativeClient-DotNet#29]
What are we supposed to use to set up AccessTokenFormat?  Example that doesn't work in 4.1.  Seems to work in 3.1

app.UseOAuthBearerAuthentication(new OAuthBearerAuthenticationOptions
            {
                AccessTokenFormat = new JwtFormat(
                    new TokenValidationParameters
                    {
                        // Check if the audience is intended to be this application
                        ValidAudiences = new [] { clientId, $"api://{clientId}" },

                        // Change below to 'true' if you want this Web API to accept tokens issued to one Azure AD tenant only (single-tenant)
                        // Note that this is a simplification for the quickstart here. You should validate the issuer. For details, 
                        // see https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore
                        ValidateIssuer = false,

                    },
                    new OpenIdConnectSecurityTokenProvider("https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration")
                ),
            });

**Comment by jmprieur** [comment]
@brentschmaltz @mafurman

**Comment by brentschmaltz** [comment]
@jrmcdona is your need to add additional audiences?
Can you share the error you are receiving.

As a note, you should be **VERY** careful about setting: **TokenValidationParameters.ValidateIssuer = false.**

**Comment by jrmcdona** [comment]
@brentschmaltz  nope.  JwtFormat class does not exist in 4.1.   Therefore this code in the 3.1 sample does not work because it uses JwtFormat which does not exist anymore.    What should I use instead in 4.1 code?

See the sample code below where it uses JwtFormat.  It will not compile in 4.1:

```
app.UseOAuthBearerAuthentication(new OAuthBearerAuthenticationOptions
{
AccessTokenFormat = new JwtFormat(
```


By the way I have a web application and not web api.   Not sure if that matters.

**Comment by mafurman** [comment]
@jrmcdona What properties do you need to set on the JwtFormat? I don't believe the class exists in 4.1, but it should be possible to add the same settings to your authentication middleware in a different way.

**Comment by jrmcdona** [comment]
@mafurman @brentschmaltz  I need to set the TokenDecryption signing keys.   My token is Microsoft first party and it is encrypted with a certificate.

If I can get that information that will be good.   Valid Audience will be good too.

**Comment by mafurman** [comment]
@jrmcdona  I believe in 4.1 the TokenValidationParameters should be a property that's directly on the options class, rather than on the JwtFormat. It should still contain both of the properties you need.

**Comment by jrmcdona** [comment]
@mafurman  how do I get a hold of that?  can I get short example of that?

**Comment by brentschmaltz** [comment]
@mafurman i see JwtFormat here: https://github.com/aspnet/AspNetKatana/blob/d196e785e277452f1382dded08ca12974d29170e/src/Microsoft.Owin.Security.Jwt/JwtFormat.cs#L17 so i am not understanding something.

**Comment by jrmcdona** [comment]
@brentschmaltz @mafurman 
Ok  I got JwtFormat working there was package confusion.

However,  IIssuerSecurityTokenProvider changed to  IIssuerSecurityKeyProvider.  So this sample code is out of date. 

Do we have an updated sample that would make this a little easier?

**Comment by brentschmaltz** [comment]
@jrmcdona @jmprieur yes, you hit upon the conceptual change from 3.x to 4.x.
We think of 'SecurityKey's' when signing SecurityTokens and relegate SecurityTokens to a collection of signed claims.

This wiki may be of some help: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/Migrating-from-Katana-(OWIN)-3.x-to-4.x

**Comment by jrmcdona** [comment]
Ok,  so if that is the case do I still need to use OpenIdConnectSecurityTokenProvider?

And then update it's implementation?   Will it be that simple?   There isn't a sample that uses SecurityKeys for UseOAuthBearerAuthentication as far as I know.

**Comment by jrmcdona** [comment]
Got it working.

```
namespace Community.Web
{
    using System.Collections.Generic;
    using System.Threading;
    using Microsoft.IdentityModel.Protocols;
    using Microsoft.IdentityModel.Tokens;
    using Microsoft.IdentityModel.Protocols.OpenIdConnect;
    using Microsoft.Owin.Security.Jwt;


    // This class is necessary because the OAuthBearer Middleware does not leverage
    // the OpenID Connect metadata endpoint exposed by the STS by default.
    public class OpenIdConnectSecurityKeyProvider: IIssuerSecurityKeyProvider
    {
        public ConfigurationManager<OpenIdConnectConfiguration> ConfigManager;
        private string _issuer;
        private IEnumerable<SecurityKey> _keys;
        private readonly string _metadataEndpoint;

        private readonly ReaderWriterLockSlim _synclock = new ReaderWriterLockSlim();

        /// <summary>
        /// OpenIdConnectSecurityKeyProvider
        /// </summary>
        /// <param name="metadataEndpoint"></param>
        public OpenIdConnectSecurityKeyProvider(string metadataEndpoint)
        {
            _metadataEndpoint = metadataEndpoint;
            ConfigManager = new ConfigurationManager<OpenIdConnectConfiguration>(metadataEndpoint, new OpenIdConnectConfigurationRetriever());

            this.RetrieveMetadata();
        }
        public string Issuer
        {
            get
            {
                RetrieveMetadata();
                _synclock.EnterReadLock();
                try
                {
                    return _issuer;
                }
                finally
                {
                    _synclock.ExitReadLock();
                }
            }
        }

        public IEnumerable<SecurityKey> SecurityKeys
        {
            get
            {
                RetrieveMetadata();
                _synclock.EnterReadLock();
                try
                {
                    return _keys;
                }
                finally
                {
                    _synclock.ExitReadLock();
                }
            }
        }

        private void RetrieveMetadata()
        {
            this._synclock.EnterWriteLock();
            try
            {
                var config = this.ConfigManager.GetConfigurationAsync().Result;
                this._issuer = config.Issuer;
                this._keys = config.SigningKeys;
            }
            finally
            {
                this._synclock.ExitWriteLock();
            }
        }
    }
}
```
