### ISSUE TITLE
Example stops short of Azure deployment

### ISSUE THREAD

**Issue by pritchie99** [AzureADQuickStarts/AppModelv2-NativeClient-DotNet#7]
Hi - great example but it stops short of deploying v2 to Azure.  Is it possible to add this, or include a link to where this is shown please?  Perhaps there is not longer the requirement to register apps in the target directory, but this is not clear to me.
I am particularly interested in WebAPI and client being "same app" using the same ID.
Every other example I've seen uses the Microsoft Graph which doesn't help me.
Also, when I attempt Option 1.1 - there is no _Tenant_ parameter in the Web.config for this sample?
Thanks, 
Paul.

**Comment by jmprieur** [comment]
@pritchie99 : you might be interested in this sample: https://github.com/azure-samples/active-directory-dotnet-native-aspnetcore-v2, which is more recent, and explains how to deploy the Web Api to Azure

**Comment by pritchie99** [comment]
Thank you - much appreciated.
